weapon_a: katana
team_a_count: 2
weapon_b: knife
team_b_count: 2
# max_simulation_seconds: 120
seed: 6
# seeds: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
# seed: 666
ai_transition_seconds: 20
debug: false
# Number of players on team A. Set to 2 for a 2v2 match.
# Number of players on team B. Set to 2 for a 2v2 or 1 for 1v2.
# Example configurations:
#   2v2 -> team_a_count: 2, team_b_count: 2
#   1v2 -> team_a_count: 1, team_b_count: 2
