name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v1
      - name: Install dependencies
        run: uv sync --all-extras --dev
      - name: Lint
        run: uv run ruff check .
      - name: Type check
        run: uv run mypy .
      - name: Tests
        run: uv run pytest --cov=.
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: .coverage
      - name: Upload videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: videos
          path: |
            out/**/*.mp4
            frames/**/*.png
          if-no-files-found: ignore
